### ISSUE TITLE
Add test for version number support

### ISSUE THREAD

**Issue by leibovic** [mozilla-services/switchboard-server#2]
I don't see any test for version number support here:
https://github.com/mozilla-services/switchboard-server/blob/master/test/manager_test.js

That is worrisome. We should make sure that feature works properly.

**Comment by milescrabill** [comment]
I'm a little confused by what you mean, but if this is related to the other issue about product version, I've added a test in 8c436d5f8aa5ce7e473455d659076b0381ad18de [here](https://github.com/mozilla-services/switchboard-server/blob/8c436d5f8aa5ce7e473455d659076b0381ad18de/test/server_test.js#L88-L101).

**Comment by milescrabill** [comment]
Is the above sufficient?
