### ISSUE TITLE
appId "org.mozilla.fennec" is matching "org.mozilla.fennec_aurora"

### ISSUE THREAD

**Issue by leibovic** [mozilla-services/switchboard-server#4]
It looks like the appId field isn't an exact match. We should make it into an exact match.

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1250289#c2

**Comment by leibovic** [comment]
We should also make sure we add a test for this. I see that there is supposedly a test case for this, but I don't think this test case is covering this substring edge case:
https://github.com/mozilla-services/switchboard-server/blob/master/test/manager_test.js#L50

**Comment by milescrabill** [comment]
I addressed this issue in the updated tests in https://github.com/mozilla-services/switchboard-server/commit/8c436d5f8aa5ce7e473455d659076b0381ad18de. This issue is just a result of our regular expressions matching being native JS RegExp matching.

**Comment by leibovic** [comment]
We should update the documentation in the switchboard-experiments repo to explain this. We also still need to flesh out the match key documentation in general. I filed an issue about that: https://github.com/mozilla-services/switchboard-experiments/issues/15
